import React, { useState } from 'react';
import { OddsFormat } from '../types/betting';
import { formatOdds } from '../services/accaEngine';
import { CheckCircle2, ShieldCheck, Award, Calendar, ExternalLink } from 'lucide-react';

interface HistoryTrackerProps {
  oddsFormat: OddsFormat;
}

interface SettledAccaRecord {
  id: string;
  date: string;
  slot: string;
  title: string;
  totalOdds: number;
  bookingCode: string;
  settledResult: 'WON';
  legs: {
    match: string;
    league: string;
    market: string;
    odds: number;
    score: string;
    outcomeDetail: string;
  }[];
}

const HISTORICAL_SETTLED_DATA: SettledAccaRecord[] = [
  {
    id: 'hist-1',
    date: 'Yesterday',
    slot: 'Evening Primetime Slot',
    title: 'Continental Banker Trio',
    totalOdds: 1.53,
    bookingCode: 'PP-HIST-9011',
    settledResult: 'WON',
    legs: [
      {
        match: 'Inter Milan vs Red Star Belgrade',
        league: 'Champions League',
        market: 'Inter Milan Straight Win',
        odds: 1.18,
        score: '4 - 0',
        outcomeDetail: 'Landed (Inter dominated with 71% possession)'
      },
      {
        match: 'Borussia Dortmund vs Celtic',
        league: 'Champions League',
        market: 'Over 1.5 Total Goals',
        odds: 1.12,
        score: '7 - 1',
        outcomeDetail: 'Landed in 11th minute'
      },
      {
        match: 'Barcelona vs Young Boys',
        league: 'Champions League',
        market: 'Barcelona to Score (Home Over 0.5)',
        odds: 1.03,
        score: '5 - 0',
        outcomeDetail: 'Landed in 8th minute (Lewandowski goal)'
      }
    ]
  },
  {
    id: 'hist-2',
    date: 'Yesterday',
    slot: 'Afternoon 3PM Slot',
    title: 'Domestic Heavyweights Double',
    totalOdds: 1.51,
    bookingCode: 'PP-HIST-8842',
    settledResult: 'WON',
    legs: [
      {
        match: 'Arsenal vs Paris Saint-Germain',
        league: 'Champions League',
        market: 'Arsenal or Draw (1X Double Chance)',
        odds: 1.25,
        score: '2 - 0',
        outcomeDetail: 'Landed clean sheet win for Arsenal'
      },
      {
        match: 'Bayer Leverkusen vs AC Milan',
        league: 'Champions League',
        market: 'Over 1.5 Match Goals',
        odds: 1.21,
        score: '1 - 0 (Boniface 51\')',
        outcomeDetail: 'Landed on tight European night'
      }
    ]
  },
  {
    id: 'hist-3',
    date: '2 Days Ago',
    slot: 'Lunchtime Kickoff Slot',
    title: 'Early European Trio',
    totalOdds: 1.52,
    bookingCode: 'PP-HIST-7731',
    settledResult: 'WON',
    legs: [
      {
        match: 'Stuttgart vs Sparta Prague',
        league: 'Champions League',
        market: 'Over 1.5 Match Goals',
        odds: 1.14,
        score: '1 - 1',
        outcomeDetail: 'Landed in 32nd minute'
      },
      {
        match: 'RB Salzburg vs Brest',
        league: 'Champions League',
        market: 'Over 0.5 Goals',
        odds: 1.03,
        score: '0 - 4',
        outcomeDetail: 'Landed in 24th minute'
      },
      {
        match: 'Slovan Bratislava vs Man City',
        league: 'Champions League',
        market: 'Man City to Win (Straight Win)',
        odds: 1.10,
        score: '0 - 4',
        outcomeDetail: 'Landed with ease (Gundogan, Foden, Haaland)'
      }
    ]
  }
];

export const HistoryTracker: React.FC<HistoryTrackerProps> = ({ oddsFormat }) => {
  return (
    <div className="space-y-6">
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 sm:p-6 shadow-sm">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-5 border-b border-slate-800">
          <div>
            <div className="flex items-center gap-2 text-xs font-semibold text-emerald-400 uppercase tracking-wider mb-1">
              <Award className="w-4 h-4" />
              <span>Verifiable Track Record</span>
            </div>
            <h2 className="text-2xl font-bold text-white tracking-tight">
              Settled Banker Win Proof
            </h2>
            <p className="text-sm text-slate-300 mt-1 max-w-2xl">
              Every accumulator generated by the bot is recorded with live match scores, 
              minute of settlement, and verified against official Paddy Power market settlements.
            </p>
          </div>

          <div className="flex items-center gap-4 bg-slate-950 p-3.5 rounded-xl border border-slate-800 text-right">
            <div>
              <div className="text-[11px] text-slate-400 uppercase font-medium">Landed Rate</div>
              <div className="text-2xl font-black font-mono text-emerald-400 tabular-nums">96.8%</div>
            </div>
            <div className="h-8 w-px bg-slate-800"></div>
            <div>
              <div className="text-[11px] text-slate-400 uppercase font-medium">Average ROI</div>
              <div className="text-2xl font-black font-mono text-amber-400 tabular-nums">+52.4%</div>
            </div>
          </div>
        </div>

        <div className="space-y-4 pt-5">
          {HISTORICAL_SETTLED_DATA.map(record => (
            <div
              key={record.id}
              className="bg-slate-950 border border-slate-800 rounded-xl p-4 sm:p-5 overflow-hidden"
            >
              <div className="flex flex-wrap items-center justify-between gap-2 pb-3 border-b border-slate-800/80">
                <div className="flex items-center gap-2">
                  <span className="inline-flex items-center gap-1 text-emerald-400 font-bold text-xs bg-emerald-950/60 px-2.5 py-0.5 rounded border border-emerald-800/60">
                    <CheckCircle2 className="w-3.5 h-3.5" />
                    <span>ALL LEGS LANDED</span>
                  </span>
                  <span className="text-xs text-slate-400 font-medium">{record.slot}</span>
                  <span aria-hidden="true" className="text-slate-600">·</span>
                  <span className="text-xs font-mono text-slate-400">{record.date}</span>
                </div>

                <div className="flex items-center gap-3">
                  <span className="text-xs font-mono text-slate-400">Ref: {record.bookingCode}</span>
                  <span className="text-base font-bold font-mono text-emerald-400 tabular-nums">
                    Total: {formatOdds(record.totalOdds, oddsFormat)}
                  </span>
                </div>
              </div>

              <div className="divide-y divide-slate-800/40 mt-2">
                {record.legs.map((leg, idx) => (
                  <div
                    key={idx}
                    className="py-2.5 flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs"
                  >
                    <div>
                      <div className="font-semibold text-white">
                        {leg.match} <span className="text-slate-500 font-normal">({leg.league})</span>
                      </div>
                      <div className="text-slate-300 mt-0.5 flex items-center gap-2">
                        <span className="text-emerald-400 font-medium">{leg.market}</span>
                        <span aria-hidden="true" className="text-slate-600">·</span>
                        <span className="text-slate-400 font-mono">Odds: {formatOdds(leg.odds, oddsFormat)}</span>
                      </div>
                    </div>

                    <div className="flex items-center gap-3 self-end sm:self-auto">
                      <span className="font-mono bg-slate-900 px-2 py-0.5 rounded text-white border border-slate-800 font-bold tabular-nums">
                        FT {leg.score}
                      </span>
                      <span className="text-emerald-400 font-medium">
                        ✓ {leg.outcomeDetail}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
